stages:
  - build  

build_job:
  stage: build
  only:
    - branches
  script:
    - 'cd ConsoleApp2'
    - '"C:\Tools\Nuget\nuget.exe" restore'
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe" ConsoleApp2.sln'  
  artifacts:
    paths:
      - 'ConsoleApp2\ConsoleApp2\bin\Debug\ConsoleApp2.exe'
 #